### ISSUE TITLE
[BUG] Importing configuration files gives always error in Strapi 4.3.4.

### ISSUE THREAD

**Issue by SalahAdDin** [boazpoolman/strapi-plugin-config-sync#64] opened 2022-08-15 16:08 UTC
### Describe the bug

Every time we try to import the configuration for our models we get an error toast, looking on the console we get this error:
```
XHRPOSThttp://localhost:1337/config-sync/import
[HTTP/1.1 500 Internal Server Error 2477ms]

	
POST
	http://localhost:1337/config-sync/import
Status
500
Internal Server Error
VersionHTTP/1.1
Transferred1.11 kB (99 B size)
Referrer Policyno-referrer
Request PriorityHighest

    	
    Access-Control-Allow-Credentials
    	true
    Access-Control-Allow-Origin
    	http://localhost:1337
    Connection
    	keep-alive
    Content-Length
    	99
    Content-Security-Policy
    	connect-src 'self' https:;script-src 'self' editor.unlayer.com;frame-src 'self' editor.unlayer.com;img-src 'self' data: blob: cdn.jsdelivr.net strapi.io dl.airtable.com res.cloudinary.com;media-src 'self' data: blob: dl.airtable.com res.cloudinary.com;default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'
    Content-Type
    	application/json; charset=utf-8
    Date
    	Mon, 15 Aug 2022 15:55:44 GMT
    Expect-CT
    	max-age=0
    Keep-Alive
    	timeout=5
    Referrer-Policy
    	no-referrer
    Strict-Transport-Security
    	max-age=31536000; includeSubDomains
    Vary
    	Origin
    X-Content-Type-Options
    	nosniff
    X-DNS-Prefetch-Control
    	off
    X-Download-Options
    	noopen
    X-Frame-Options
    	SAMEORIGIN
    X-Permitted-Cross-Domain-Policies
    	none
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-GB,tr;q=0.8,es;q=0.5,en;q=0.3
    Authorization
    	Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjYwNTc4ODgyLCJleHAiOjE2NjMxNzA4ODJ9.W6jgkZ3Ow0b3D-LynqtxQe08YpCB2-Sj9Om0mrav1IU
    Connection
    	keep-alive
    Content-Length
    	2790
    Content-Type
    	application/json
    Host
    	localhost:1337
    Origin
    	http://localhost:1337
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    User-Agent
    	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0
```
And going to the network, we can see this.
<img width="1184" alt="Screen Shot 2022-08-15 at 19 00 13" src="https://user-images.githubusercontent.com/5034215/184670993-8ea9baf8-c69b-464a-a348-711991959e07.png">

Moving to the content manager, we get two behaviours:

1. The configuration settings were properly loaded.
2. The admin user lost all the permission and cannot see anything.

### Steps to reproduce the behavior

1. Go to Content Manager.
3. Click on Config Syng > Tools.
4. Select all the files you want to import.
5. Import them.
6. See the toast error.
7. Go to Console.
8. Check the error.
9. Go to Network.
10. Check the error.

### Expected behavior

It shouldn't give an error at importing.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.20.0
- Strapi version: 4.3.4
- Plugin version: 2.0.8
- Database: PostgreSQL 13.7
- Operating system: Alpine Linux v3.16

### Additional context
It is always a clean installation with a empty database.

**Comment by boazpoolman** [comment] 2022-08-15 16:14
Hi @SalahAdDin 

Thanks for reporting the issue.

Could you also provide me with the Strapi server logging?
Probably there is a more descriptive error there.

**Comment by SalahAdDin** [comment] 2022-08-15 16:16
The files that are identical to the database or have "Only database" status should not be selectable for importing; when you don't uncheck them, it can crunch all the admin configuration(hence, we had the second aforementioned behavior).

**Comment by SalahAdDin** [comment] 2022-08-15 16:19
> Hi @SalahAdDin
> 
> Thanks for reporting the issue.
> 
> Could you also provide me with the Strapi server logging? Probably there is a more descriptive error there.

```
[2022-08-15 16:13:17.724] error: error: insert into "admin_permissions" ("action", "conditions", "created_at", "id", "properties", "subject", "updated_at") values ($1, $2, $3, $4, $5, $6, $7) returning "id" - duplicate key value violates unique constraint "admin_permissions_pkey"
Error: error: insert into "admin_permissions" ("action", "conditions", "created_at", "id", "properties", "subject", "updated_at") values ($1, $2, $3, $4, $5, $6, $7) returning "id" - duplicate key value violates unique constraint "admin_permissions_pkey"
    at Object.importSingleConfig (/srv/app/node_modules/strapi-plugin-config-sync/server/services/main.js:234:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /srv/app/node_modules/strapi-plugin-config-sync/server/controllers/config.js:57:7
    at async Promise.all (index 7)
    at async Object.importAll (/srv/app/node_modules/strapi-plugin-config-sync/server/controllers/config.js:56:5)
    at async returnBodyMiddleware (/srv/app/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/srv/app/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async transform (/srv/app/node_modules/strapi-plugin-transformer/server/middleware/transform.js:9:2)
    at async /srv/app/node_modules/@strapi/strapi/lib/middlewares/body.js:51:9
    at async /srv/app/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5
    at async /srv/app/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
    at async cors (/srv/app/node_modules/@koa/cors/index.js:95:16)
    at async /srv/app/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
    at async session (/srv/app/node_modules/koa-session/index.js:41:7)
    at async /srv/app/node_modules/@strapi/strapi/lib/services/metrics/middleware.js:29:5
```

Here is something problematic, we are not importing any related admin file:
<img width="665" alt="Screen Shot 2022-08-15 at 19 19 27" src="https://user-images.githubusercontent.com/5034215/184674125-c610ed3c-780c-417e-8356-d4db114f2664.png">

**Comment by boazpoolman** [comment] 2022-08-15 16:22
Hmm.. Allright. So, there is not a single admin-role file in your `config/sync/` dir?
That means that if you import this it will delete the admin-roles. That's how the plugin was intended.
If you don't want to sync the admin-roles you should exclude them through the settings.

**Comment by SalahAdDin** [comment] 2022-08-15 19:11
> Hmm... Alright. So, there is not a single admin-role file in your `config/sync/` dir? That means that if you import this it will delete the admin-roles. That's how the plugin was intended. If you don't want to sync the admin-roles you should exclude them through the settings.

Yeah, we don't have such a file in the sync folder; hence, I don't understand the **Strapi** logs.

**Comment by boazpoolman** [comment] 2022-08-15 19:15
Could you please use the `excludedTypes` setting to exclude the admin-role type and try again?
https://github.com/boazpoolman/strapi-plugin-config-sync#excluded-types

**Comment by SalahAdDin** [comment] 2022-08-15 20:15
> Could you please use the `excludedTypes` setting to exclude the admin-role type and try again? https://github.com/boazpoolman/strapi-plugin-config-sync#excluded-types

I'm having the same problem yet:
<img width="1247" alt="Screen Shot 2022-08-15 at 23 15 23" src="https://user-images.githubusercontent.com/5034215/184710835-55bec4f0-f294-4b99-b4e3-9e0b351bb686.png">

**Comment by boazpoolman** [comment] 2022-08-16 07:25
Weirddd. Really don't get it now.

**Comment by SalahAdDin** [comment] 2022-08-16 09:47
> Weird. Really don't get it now.
> 
> I'll try investigating as soon as I have some time.

And the import process wasn't done in Bootstrap. 

Maybe, it is related to that, how can we check the configuration is working?

**Comment by boazpoolman** [comment] 2022-08-16 10:28
Whether you import during the bootstrap phase or not, the same code is used.

Could you try something out for me?

Try importing through the CLI using the `-p` flag to partially import only the content manager config.

**Comment by SalahAdDin** [comment] 2022-08-16 15:03
> Whether you import during the bootstrap phase or not, the same code is used.
> 
> Could you try something out for me?
> 
> Try importing through the CLI using the `-p` flag to partially import only the content manager config.

Well, this is my first try:
```
$ config-sync import -p 'core-store.plugin_content_manager_configuration_components##content.content.json,core-store.plugin_content_manager_configuration_components##content.experience.json,core-store.plugin_content_manager_configuration_components##content.personal-information.json,core-store.plugin_content_manager_configuration_components##fields.address.json,core-store.plugin_content_manager_configuration_components##fields.skill.json,core-store.plugin_content_manager_configuration_components##fields.telephone.json,core-store.plugin_content_manager_configuration_components##fields.url.json,core-store.plugin_content_manager_configuration_components##shared.meta-social.json,core-store.plugin_content_manager_configuration_components##shared.seo.json,core-store.plugin_content_manager_configuration_content_types##api##category.category.json,core-store.plugin_content_manager_configuration_content_types##api##page.page.json,core-store.plugin_content_manager_configuration_content_types##api##project.project.json,core-store.plugin_content_manager_configuration_content_types##api##tag.tag.json'
Starting the compilation for TypeScript files in /srv/app
[2022-08-16 14:45:41.903] warn: [strapi-plugin-config-sync]: You can't use the 'importOnBootstrap' setting in the development env.
[2022-08-16 14:45:45.322] info: --------  MIGRATION STARTED  --------
[2022-08-16 14:45:45.341] warn: No migration directory found.
[2022-08-16 14:45:45.342] info: --------  MIGRATION FINISHED  --------
[2022-08-16 14:45:45.401] info: [website builder] manual trigger enabled
[notice] There are no changes for the specified config.
Done in 62.23s.
/srv/app # yarn cs diff
yarn run v1.22.19
$ config-sync diff
Starting the compilation for TypeScript files in /srv/app
[2022-08-16 14:50:23.179] warn: [strapi-plugin-config-sync]: You can't use the 'importOnBootstrap' setting in the development env.
[2022-08-16 14:50:26.135] info: --------  MIGRATION STARTED  --------
[2022-08-16 14:50:26.138] warn: No migration directory found.
[2022-08-16 14:50:26.139] info: --------  MIGRATION FINISHED  --------
[2022-08-16 14:50:26.159] info: [website builder] manual trigger enabled
╔═════════════════════════════════════════════════════════════════╤════════════════════╗
║ Name                                                            │ State              ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_components::co… │ Different          ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_components::co… │ Different          ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_components::co… │ Different          ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_components::fi… │ Different          ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_components::fi… │ Different          ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_components::fi… │ Different          ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_components::fi… │ Different          ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Different          ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Different          ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Different          ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Different          ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ i18n-locale.es                                                  │ Only in sync dir   ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ i18n-locale.tr                                                  │ Only in sync dir   ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ user-role.authenticated                                         │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ user-role.public                                                │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.strapi_content_types_schema                          │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_upload_settings                               │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_sitemap_settings                              │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_i18n_default_locale                           │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_users-permissions_email                       │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_users-permissions_advanced                    │ Only in DB         ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.core_admin_auth                                      │ Only in DB         ║
╚═════════════════════════════════════════════════════════════════╧════════════════════╝
Done in 62.54s.
/srv/app # 
```

I think we are doing it wrong, so we will try file by file.

**Comment by SalahAdDin** [comment] 2022-08-16 15:08
Now, the second try:
```
/srv/app # yarn cs import -p core-store.plugin_content_man
ager_configuration_components##content.content
yarn run v1.22.19
$ config-sync import -p 'core-store.plugin_content_manager_configuration_components##content.content'
Starting the compilation for TypeScript files in /srv/app
[2022-08-16 15:07:08.655] warn: [strapi-plugin-config-sync]: You can't use the 'importOnBootstrap' setting in the development env.
[2022-08-16 15:07:12.390] info: --------  MIGRATION STARTED  --------
[2022-08-16 15:07:12.394] warn: No migration directory found.
[2022-08-16 15:07:12.395] info: --------  MIGRATION FINISHED  --------
[2022-08-16 15:07:12.419] info: [website builder] manual trigger enabled
[notice] There are no changes for the specified config.
Done in 58.21s.
```

**Comment by boazpoolman** [comment] 2022-08-16 15:16
I believe the command is incomplete. Can you try this:

```
yarn cs import -p core-store.plugin_content_manager_configuration_content_types::api::category.category
```

**Comment by SalahAdDin** [comment] 2022-08-16 18:07
> yarn cs import -p core-store.plugin_content_manager_configuration_content_types::api::category.category

crack!

Yeah, I worked:
```
$ config-sync import -p core-store.plugin_content_manager_configuration_content_types::api::category.category
Starting the compilation for TypeScript files in /srv/app
[2022-08-16 17:54:26.075] warn: [strapi-plugin-config-sync]: You can't use the 'importOnBootstrap' setting in the development env.
[2022-08-16 17:54:29.221] info: --------  MIGRATION STARTED  --------
[2022-08-16 17:54:29.224] warn: No migration directory found.
[2022-08-16 17:54:29.224] info: --------  MIGRATION FINISHED  --------
[2022-08-16 17:54:29.244] info: [website builder] manual trigger enabled
╔═════════════════════════════════════════════════════════════════╤════════════════════╗
║ Name                                                            │ Action             ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Update             ║
╚═════════════════════════════════════════════════════════════════╧════════════════════╝ 

? Are you sure you want to import the config changes? Yes

[notice] Imported core-store.plugin_content_manager_configuration_content_types::api::category.category
[success] Finished import
Done in 62.13s.

```

I will test the others then.

**Comment by SalahAdDin** [comment] 2022-08-16 18:13
Now,

```
/srv/app # yarn cs import -p core-store.plugin_content_man
ager_configuration_components::content.experience,core-sto
re.plugin_content_manager_configuration_components::conten
t.personal-information,core-store.plugin_content_manager_c
onfiguration_components::fields.address,core-store.plugin_
content_manager_configuration_components::fields.skill,cor
e-store.plugin_content_manager_configuration_components::f
ields.telephone,core-store.plugin_content_manager_configur
ation_components::fields.url,core-store.plugin_content_man
ager_configuration_components::shared.meta-social,core-sto
re.plugin_content_manager_configuration_components::shared
.seo,core-store.plugin_content_manager_configuration_conte
nt_types::api::category.category,core-store.plugin_content
_manager_configuration_content_types::api::page.page,core-
store.plugin_content_manager_configuration_content_types::
api::project.project,core-store plugin_content_manager_con
figuration_content_types::api::tag.tag
yarn run v1.22.19
$ config-sync import -p core-store.plugin_content_manager_configuration_components::content.experience,core-store.plugin_content_manager_configuration_components::content.personal-information,core-store.plugin_content_manager_configuration_components::fields.address,core-store.plugin_content_manager_configuration_components::fields.skill,core-store.plugin_content_manager_configuration_components::fields.telephone,core-store.plugin_content_manager_configuration_components::fields.url,core-store.plugin_content_manager_configuration_components::shared.meta-social,core-store.plugin_content_manager_configuration_components::shared.seo,core-store.plugin_content_manager_configuration_content_types::api::category.category,core-store.plugin_content_manager_configuration_content_types::api::page.page,core-store.plugin_content_manager_configuration_content_types::api::project.project,core-store plugin_content_manager_configuration_content_types::api::tag.tag
Starting the compilation for TypeScript files in /srv/app
[2022-08-16 18:12:58.430] warn: [strapi-plugin-config-sync]: You can't use the 'importOnBootstrap' setting in the development env.
[2022-08-16 18:13:01.371] info: --------  MIGRATION STARTED  --------
[2022-08-16 18:13:01.374] warn: No migration directory found.
[2022-08-16 18:13:01.375] info: --------  MIGRATION FINISHED  --------
[2022-08-16 18:13:01.395] info: [website builder] manual trigger enabled
╔═════════════════════════════════════════════════════════════════╤════════════════════╗
║ Name                                                            │ Action             ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_components::co… │ Update             ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_components::co… │ Update             ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_components::fi… │ Update             ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_components::fi… │ Update             ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_components::fi… │ Update             ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_components::fi… │ Update             ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Update             ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Update             ║
╚═════════════════════════════════════════════════════════════════╧════════════════════╝ 

? Are you sure you want to import the config changes? Yes

[notice] Imported core-store.plugin_content_manager_configuration_components::content.personal-information
[notice] Imported core-store.plugin_content_manager_configuration_components::fields.address
[notice] Imported core-store.plugin_content_manager_configuration_components::fields.skill
[notice] Imported core-store.plugin_content_manager_configuration_components::fields.telephone
[notice] Imported core-store.plugin_content_manager_configuration_components::content.experience
[notice] Imported core-store.plugin_content_manager_configuration_components::fields.url
[notice] Imported core-store.plugin_content_manager_configuration_content_types::api::page.page
[notice] Imported core-store.plugin_content_manager_configuration_content_types::api::project.project
[success] Finished import
Done in 72.52s.
```

**Comment by SalahAdDin** [comment] 2022-08-16 18:16
And:
```
/srv/app # yarn cs import -p core-store.plugin_content_man
ager_configuration_components::content.content
yarn run v1.22.19
$ config-sync import -p core-store.plugin_content_manager_configuration_components::content.content
Starting the compilation for TypeScript files in /srv/app
[2022-08-16 18:15:49.703] warn: [strapi-plugin-config-sync]: You can't use the 'importOnBootstrap' setting in the development env.
[2022-08-16 18:15:52.667] info: --------  MIGRATION STARTED  --------
[2022-08-16 18:15:52.670] warn: No migration directory found.
[2022-08-16 18:15:52.671] info: --------  MIGRATION FINISHED  --------
[2022-08-16 18:15:52.690] info: [website builder] manual trigger enabled
╔═════════════════════════════════════════════════════════════════╤════════════════════╗
║ Name                                                            │ Action             ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_components::co… │ Update             ║
╚═════════════════════════════════════════════════════════════════╧════════════════════╝ 

? Are you sure you want to import the config changes? Yes

[notice] Imported core-store.plugin_content_manager_configuration_components::content.content
[success] Finished import
Done in 67.39s.

```

**Comment by SalahAdDin** [comment] 2022-08-16 20:10
And:
```
/srv/app # yarn cs import -p core-store.plugin_content_man
ager_configuration_content_types::api::tag.tag
yarn run v1.22.19
$ config-sync import -p core-store.plugin_content_manager_configuration_content_types::api::tag.tag
Starting the compilation for TypeScript files in /srv/app
[2022-08-16 20:09:43.152] warn: [strapi-plugin-config-sync]: You can't use the 'importOnBootstrap' setting in the development env.
[2022-08-16 20:09:47.003] info: --------  MIGRATION STARTED  --------
[2022-08-16 20:09:47.008] warn: No migration directory found.
[2022-08-16 20:09:47.009] info: --------  MIGRATION FINISHED  --------
[2022-08-16 20:09:47.036] info: [website builder] manual trigger enabled
╔═════════════════════════════════════════════════════════════════╤════════════════════╗
║ Name                                                            │ Action             ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ core-store.plugin_content_manager_configuration_content_types:… │ Update             ║
╚═════════════════════════════════════════════════════════════════╧════════════════════╝ 

? Are you sure you want to import the config changes? Yes

[notice] Imported core-store.plugin_content_manager_configuration_content_types::api::tag.tag
[success] Finished imp
```

**Comment by SalahAdDin** [comment] 2022-08-16 20:15
Finally, I found the ba*** problem:
```
/srv/app # yarn cs import -p i18n-locale.tr,i18n-locale.es
yarn run v1.22.19
$ config-sync import -p i18n-locale.tr,i18n-locale.es
Starting the compilation for TypeScript files in /srv/app
[2022-08-16 20:12:17.884] warn: [strapi-plugin-config-sync]: You can't use the 'importOnBootstrap' setting in the development env.
[2022-08-16 20:12:21.801] info: --------  MIGRATION STARTED  --------
[2022-08-16 20:12:21.815] warn: No migration directory found.
[2022-08-16 20:12:21.815] info: --------  MIGRATION FINISHED  --------
[2022-08-16 20:12:21.871] info: [website builder] manual trigger enabled
╔═════════════════════════════════════════════════════════════════╤════════════════════╗
║ Name                                                            │ Action             ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ i18n-locale.tr                                                  │ Create             ║
╟─────────────────────────────────────────────────────────────────┼────────────────────╢
║ i18n-locale.es                                                  │ Create             ║
╚═════════════════════════════════════════════════════════════════╧════════════════════╝ 

? Are you sure you want to import the config changes? Yes

[error] Something went wrong during the import. Error: error: insert into "admin_permissions" ("action", "conditions", "created_at", "id", "properties", "subject", "updated_at") values ($1, $2, $3, $4, $5, $6, $7) returning "id" - duplicate key value violates unique constraint "admin_permissions_pkey"
Done in 77.11s.
```

Local files are the problem!

**Comment by boazpoolman** [comment] 2022-08-17 07:40
Great! Thanks for debugging. I can work with this.

**Comment by boazpoolman** [comment] 2022-08-18 08:55
I can't reproduce..

Can you share the contents of the `i18n-locale.tr.json` and `i18n-localte.es.json` files?

**Comment by SalahAdDin** [comment] 2022-08-18 10:28
> I can't reproduce..
> 
> Can you share the contents of the `i18n-locale.tr.json` and `i18n-localte.es.json` files?

It is super basic:
```
{
  "name": "Spanish (es)",
  "code": "es"
}
```
And
```
{
  "name": "Turkish (tr)",
  "code": "tr"
}
```

**Comment by boazpoolman** [comment] 2022-08-18 10:55
Hmm.. Weird. If I create those two files and import them it works on my end.

**Comment by boazpoolman** [comment] 2022-08-18 11:08
Can you try creating a new locale from the Admin interface?

Does that work?

**Comment by SalahAdDin** [comment] 2022-08-18 12:44
> Can you try creating a new locale from the Admin interface?
> 
> Does that work?
> 
> By doing that you are pretty much doing exactly the same DB query. Though you're not doing it through the config-sync plugin through the i18n plugin.
> 
> So if that gives you the same error it is not an issue related to this plugin perse.

Actually, I did it before and I haven't had any problem with it, so, I exported my configuration files(including both language files), and I get the problem.

**Comment by boazpoolman** [comment] 2022-08-18 13:13
I just don't get it 😢

**Comment by SalahAdDin** [comment] 2022-08-18 13:21
> I just don't get it 😢

Wait, I got a bug: I can't see all the models in the content manager: there are two visible, and they both are not localizable(`i18n` disabled).

It seems the problem is related to the plugin.

**Comment by boazpoolman** [comment] 2022-08-18 13:28
You somehow have created a corrupted DB.
This is either because of missing permissions or missing config.
It is probably corrupted by using a method from this plugin (import/export).
Though I can't reproduce how to corrupt the DB.

**Comment by SalahAdDin** [comment] 2022-08-19 14:09
> You somehow have created a corrupted DB. This is either because of missing permissions or missing config. It is probably corrupted by using a method from this plugin (import/export). Though I can't reproduce how to corrupt the DB.
Was it corrupted before or after importing the localization files?

**Comment by SalahAdDin** [comment] 2022-08-20 11:58
> You somehow have created a corrupted DB. This is either because of missing permissions or missing config. It is probably corrupted by using a method from this plugin (import/export). Though I can't reproduce how to corrupt the DB.

Was it corrupted before or after importing the localization files? Cause before importing those localization-related files, we didn't have any problems.

**Comment by boazpoolman** [comment] 2022-08-30 19:42
I think it allready was corrupted. I hope you have been able to work around this by now. I don’t expect this to be an issue with the plugin as it is, but rather an issue that was raised by using a feature of the plugin.

**Comment by SalahAdDin** [comment] 2022-08-31 09:00
> I think it already was corrupted. I hope you have been able to work around this by now. I don’t expect this to be an issue with the plugin as it is, but rather an issue that was raised by using a feature of the plugin.

But, if it was already corrupted, I mean either import is corrupting the database or export is producing corrupted files.

**Comment by boazpoolman** [comment] 2022-09-06 19:48
I feel like it is more about the way you're exporting/importing.

Seeing as you here only have core-store and i18n-locale config files in the config/sync folder, in an attempt to only have those files be tracked with the plugin.
Though after then running a clean `yarn cs import` you effectively delete the UP roles and admin roles. I think this corrupted your DB.

This plugin really features a all-or-nothing approach.
If you want to exclude certain configs you have to do that via [the plugin config](https://github.com/boazpoolman/strapi-plugin-config-sync#-settings).

PS:
If you're able to give me a list of steps on how to reproduce this starting from a fresh install of Strapi I will be happy to take a look and fix the issue 🙂

**Comment by SalahAdDin** [comment] 2022-09-07 09:17
> I feel like it is more about the way you're exporting/importing.
> 
> Seeing as you here only have core-store and i18n-locale config files in the config/sync folder, in an attempt to only have those files be tracked with the plugin. Though after then running a clean `yarn cs import` you effectively delete the UP roles and admin roles. I think this corrupted your DB.
> 
> This plugin really features an all-or-nothing approach. If you want to exclude certain configs you have to do that via [the plugin config](https://github.com/boazpoolman/strapi-plugin-config-sync#-settings).
> 
> PS: If you're able to give me a list of steps on how to reproduce this starting from a fresh install of Strapi I will be happy to take a look and fix the issue 🙂

We will check it soon, thanks.

**Comment by boazpoolman** [comment] 2022-12-01 11:59
Hi @SalahAdDin,

Have you been able to write up some steps to reproduce this issue from a fresh Strapi install?

**Comment by SalahAdDin** [comment] 2022-12-01 12:35
> Hi @SalahAdDin,
> 
> Have you been able to write up some steps to reproduce this issue from a fresh Strapi install?

Actually, I reported my last errors as a feature request. I mean, I did everything again in a fresh install with the last version and was careful about importing only from files, and I didn't have any bugs.

I am using `SQLite`, maybe it could be decisive for this case, but I'm not sure.

**Comment by boazpoolman** [comment] 2022-12-01 12:46
OK. Then I think we can close this issue as we are not able to reproduce it and nobody reported the same issue. Thanks.

**Closed** 2022-12-01 12:47 UTC
Labels: bug, can’t reproduce
